<?php

namespace DevLeaguesBundle\Repository\User;

/**
 * UserTechnologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTechnologyRepository extends \Doctrine\ORM\EntityRepository
{
}
