devleagues:
    resource: "@DevLeaguesBundle/Controller/"
    type:     annotation
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

avanzu_admin:
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"
