dev_leagues:
    resource: "@DevLeaguesBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

avanzu_admin:
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
