# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    devleagues.form.registration:
        class: DevLeaguesBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: devleagues_user_registration }
